#!/usr/bin/python
""" Validates the NIST data feed
1. Against their schema.
This uses the schemas mentioned here: https://nvd.nist.gov/vuln/Data-Feeds/JSON-feed-changelog
2. Against the provided metadata, including the sha256sum
"""
import hashlib
import json
import os
import unittest
from zipfile import ZipFile
from jsonschema import validate
from jsonschema.exceptions import ValidationError

try:
    from urllib2 import urlopen
except ImportError:
    from urllib.request import urlopen

NVD_SCHEMA = "https://scap.nist.gov/schema/nvd/feed/1.1/nvd_cve_feed_json_1.1.schema"
NVD_2019_META = "https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2020.meta"


# NVD feeds from "https://nvd.nist.gov/vuln/data-feeds#JSON_FEED" but stored locally
DISK_LOCATION_DEFAULT = os.path.join(os.path.expanduser("~"), ".cache", "cvedb")
LATEST_NVD = os.path.join(DISK_LOCATION_DEFAULT, "nvd", "nvdcve-1.1-2020.json")
NVD_FILE = "nvdcve-1.1-2020.json"


class TestJSON(unittest.TestCase):
    def test_json_validation(self):
        """ Validate latest nvd json file against their published schema """
        # Download the schema
        schema = json.loads(urlopen(NVD_SCHEMA).read().decode("utf-8"))
        print("Loaded schema")

        # Open the latest nvd zipfile on disk
        for year in years:
            with json_zip.open(NVD_FILE) as json_file:
                nvd_json = json.loads(json_file.read().decode("utf-8"))
                print("Loaded json")

                # Validate -- will raise a ValidationError if not valid
                try:
                    validate(nvd_json, schema)
                    print("Validation complete")
                except ValidationError as ve:
                    print(ve)
                    self.fail("Validation error occured")
